/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  api: {
    Auth: () => import('#controllers/api/auth_controller'),
    Drops: () => import('#controllers/api/drops_controller'),
    Products: () => import('#controllers/api/products_controller'),
  },
  Home: () => import('#controllers/home_controller'),
}
